#
# hotmaps/toolbox-backend image Dockerfile
#
#

#
# hotmaps/cm image Dockerfile
#
#

FROM geographica/gdal2:latest

ENV CELERY_BROKER_URL amqp://admin:mypass@rabbit:5672/
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true
MAINTAINER lesly Houndole <lesly.houndole@crem.ch>

# setup volume
RUN mkdir -p /data
VOLUME /data

# Build commands
RUN apt-get update && apt-get dist-upgrade -y && apt-get autoremove -y

# Install required software

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    software-properties-common \
    wget \
    ca-certificates \
    gcc \
    git \
    && apt-get autoremove \
    && apt-get clean

# Setup app server
RUN mkdir -p /data

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    software-properties-common \
    wget

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py

# Install required python modules
RUN mkdir /api
RUN mkdir /api/requirements
RUN mkdir /api/requirements/celery

COPY requirements/celery/requirements.txt /api/requirements/celery/requirements.txt
COPY requirements/requirements.txt /api/requirements/requirements.txt

RUN pip install -r /api/requirements/celery/requirements.txt

# Copy app source code

COPY . /api
WORKDIR /api
RUN ls

ENTRYPOINT celery -A celery_worker.celery worker --loglevel=info